### ISSUE TITLE
ルームのアーカイブ化

### ISSUE THREAD

**Issue by tooooofu24** [tooooofu24/fripo#26]
どんな形で保存するか確認しなきゃダメ。

**Comment by tooooofu24** [comment]
これ、いるか？いらなくないか？

**Comment by tkc-alien** [comment]
履歴取得機能を付ける付けないに関わらず、運営がプレーデータを管理できた方がいい（お題の精度とかライフごとのターン数の傾向とかの分析）ので、アーカイブは残したいです。

**Comment by tooooofu24** [comment]
なるほど。仕様考える

**Comment by tooooofu24** [comment]
一旦βまでは丸ごとアーカイブする機能だけ作る
